### ISSUE TITLE
"BGP is not a protocol"

### ISSUE THREAD

**Issue by simonszu** [stephank/nagios-bird#1]
Hi,

i am trying to setup this plugin in my Icinga installation to monitor a bird with some BGP and one OSPF connection. However, i have trouble setting it up. 
When i execute `check_bird_proto.pl -p bgp` i get _BIRD_PROTO CRITICAL - 9001 syntax error_
When i execute `check_bird_proto.pl -p BGP` i get _BIRD_PROTO CRITICAL - 9002 BGP is not a protocol_.
How do i query bird for BGP protocol? The same happens with OSPF.
I am noticing you are parsing the output for some kind of "1002-line". However, i don't have any line starting with 1002, maybe that's the problem?

**Comment by stephank** [comment]
The `-p` options takes a protocol instance name. So perhaps your protocol instance is not actually named `bgp` or `BGP`, even if it is a BGP protocol? Try looking at the output of: `birdc show protocols`

I'm no longer maintaining any BIRD installations, so this project is unfortunately dormant as well. I'm afraid I cannot test to see if this is an actual bug.
